### ISSUE TITLE
Ajustes no retorno do responseEntity

### ISSUE THREAD

**Issue by oliveiralex** [wagnerpires/dsclientes#1]
Caro Wagner, tudo bem? 

Seu trabalho foi aceito, parabéns! Porém, para ficar 100%, é necessário retornar o objeto ClientDTO no responseEntity ao inserir um novo cliente ou editar um cliente existente. Além disso, na busca paginada, está retornando somente o id e nome, conforme o exemplo abaixo:
```
[
    {
        "id": 1,
        "name": "Wagner Alves Pires"
    },
    {
        "id": 2,
        "name": "Miramar Maria Souza Neto Alves"
    },
    ....
]
```

Abraço e bons estudos

**Comment by wagnerpires** [comment]
Sim ainda falta o dto nesses casos... Vou ajustar... Obrigado...

Obter o Outlook para Android<https://aka.ms/AAb9ysg>

________________________________
From: Alexandre ***@***.***>
Sent: Monday, May 17, 2021 3:18:39 PM
To: wagnerpires/dsclientes ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wagnerpires/dsclientes] Ajustes no retorno do responseEntity (#1)


Caro Wagner, tudo bem?

Seu trabalho foi aceito, parabéns! Porém, para ficar 100%, é necessário retornar o objeto ClientDTO no responseEntity ao inserir um novo cliente ou editar um cliente existente. Além disso, na busca paginada, está retornando somente o id e nome, conforme o exemplo abaixo:

[

    {

        "id": 1,

        "name": "Wagner Alves Pires"

    },

    {

        "id": 2,

        "name": "Miramar Maria Souza Neto Alves"

    },

    ....

]



Abraço e bons estudos

**Comment by wagnerpires** [comment]
Correções efetuadas... Pode conferir e me dar um feedback?

Grato


Wagner Pires


________________________________
De: Alexandre ***@***.***>
Enviado: segunda-feira, 17 de maio de 2021 15:18
Para: wagnerpires/dsclientes ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [wagnerpires/dsclientes] Ajustes no retorno do responseEntity (#1)


Caro Wagner, tudo bem?

Seu trabalho foi aceito, parabéns! Porém, para ficar 100%, é necessário retornar o objeto ClientDTO no responseEntity ao inserir um novo cliente ou editar um cliente existente. Além disso, na busca paginada, está retornando somente o id e nome, conforme o exemplo abaixo:

[

    {

        "id": 1,

        "name": "Wagner Alves Pires"

    },

    {

        "id": 2,

        "name": "Miramar Maria Souza Neto Alves"

    },

    ....

]



Abraço e bons estudos

**Comment by oliveiralex** [comment]
Olá Wagner,
As correções foram efetuadas com sucesso! Parabéns
Vou encerrar a issue.

Abraço
